# Generated by Django 5.0.7 on 2024-08-30 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_color_gallery_size_specification'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gallery',
            options={'verbose_name_plural': 'Product Images'},
        ),
    ]
