# Generated by Django 5.0.7 on 2024-09-01 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_coupon_notification_productfaq_review_wishlist'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={'verbose_name_plural': 'Reviews & Ratings'},
        ),
    ]
