# Generated by Django 5.0.7 on 2024-09-05 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_tax'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tax',
            options={'ordering': ['country'], 'verbose_name_plural': 'Taxes'},
        ),
    ]
